apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --enable-leader-election
        env:
        - name: BMC_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: bmc-config
              key: tokenURL
        - name: BMC_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: bmc-config
              key: endpointURL 
        - name: BMC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: bmc-config
              key: clientID
        - name: BMC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: bmc-config
              key: clientSecret
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-config
  namespace: system
type: Opaque
stringData:
  tokenURL: "https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token"
  endpointURL: "https://api.phoenixnap.com/bmc/v1/"
  clientID: "YOUR_CLIENT_ID"
  clientSecret: "YOUR_CLIENT_SECRET"
