
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bmc-api-phoenixnap-com-v1-server
  failurePolicy: Fail
  name: mserver.kb.io
  rules:
  - apiGroups:
    - bmc.api.phoenixnap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-bmc-api-phoenixnap-com-v1-server
  failurePolicy: Fail
  name: vserver.kb.io
  rules:
  - apiGroups:
    - bmc.api.phoenixnap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servers
